---
- name: Directory for jail flavour "bsdploy_base"
  file: dest=/usr/jails/flavours/bsdploy_base state=directory owner=root group=wheel

- name: Pkg in bsdploy_base flavour
  command: "tar -x -C /usr/jails/flavours/bsdploy_base --chroot --exclude '+*' -f /var/cache/pkg/All/pkg.txz creates=/usr/jails/flavours/bsdploy_base/usr/local/sbin/pkg"

- name: The .ssh directory for root in bsdploy_base flavour
  file:
    dest: "/usr/jails/flavours/bsdploy_base/{{ploy_root_home_path}}/.ssh"
    state: directory
    mode: "0600"
    owner: "{{ploy_root_user_name}}"
    group: wheel

- name: The etc directory in bsdploy_base flavour
  file: dest=/usr/jails/flavours/bsdploy_base/etc state=directory owner=root group=wheel
- name: The etc/ssh directory in bsdploy_base flavour
  file: dest=/usr/jails/flavours/bsdploy_base/etc/ssh state=directory owner=root group=wheel

- copy: src=make.conf dest=/usr/jails/flavours/bsdploy_base/etc/make.conf owner=root group=wheel
- file: dest=/usr/jails/flavours/bsdploy_base/usr/local/etc/pkg/repos state=directory owner=root group=wheel
- template: src=pkg.conf dest=/usr/jails/flavours/bsdploy_base/usr/local/etc/pkg.conf owner=root group=wheel
- template: src=FreeBSD.conf dest=/usr/jails/flavours/bsdploy_base/usr/local/etc/pkg/repos/FreeBSD.conf owner=root group=wheel


#
# configure bsdploy_base flavour
# TODO: rename to ``bsdploy_base``
#

- name: rc.conf for bsdploy_base flavour
  copy: src=base_flavour_rc.conf dest=/usr/jails/flavours/bsdploy_base/etc/rc.conf owner=root group=wheel
- name: sshd_config for bsdploy_base flavour
  copy: src=base_flavour_sshd_config dest=/usr/jails/flavours/bsdploy_base/etc/ssh/sshd_config owner=root group=wheel
- name: motd for bsdploy_base flavour
  copy: src=base_flavour_motd dest=/usr/jails/flavours/bsdploy_base/etc/motd owner=root group=wheel
- name: copy some settings from host to bsdploy_base flavour
  shell: cmp -s {{ item.src }} {{ item.dest }} || cp -v {{ item.src }} {{ item.dest }}
  register: _cp_settings_result
  changed_when: _cp_settings_result.stdout|default() != ''
  with_items:
    - { src: "/etc/resolv.conf", dest: "/usr/jails/flavours/bsdploy_base/etc/resolv.conf" }
    - { src: "/{{ploy_root_home_path}}/.ssh/authorized_keys", dest: "/usr/jails/flavours/bsdploy_base{{ploy_root_home_path}}/.ssh/authorized_keys" }
