---
- name: bind host sshd to primary ip
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^ListenAddress
    line: 'ListenAddress {{ ploy_jail_host_sshd_listenaddress }}'
  notify: restart sshd

- { include: ntpd.yml, tags: ntpd }
- { include: obsolete-ipf.yml, tags: pf }
- { include: pf.yml, tags: pf }

- name: Add lo1 to rc.conf
  sysrc:
    name: cloned_interfaces
    value: lo1
  notify: restart network

- meta: flush_handlers

# The sysctl module in ansible adds spaces around the equal sign in
# /etc/sysctl.conf which breaks in FreeBSD 10, so we do this manually
- name: Enable security.jail.allow_raw_sockets
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: ^security.jail.allow_raw_sockets\s*=
    line: security.jail.allow_raw_sockets=1
  notify: reload sysctl
  tags: sysctl
- name: Enable security.jail.sysvipc_allowed
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: ^security.jail.sysvipc_allowed\s*=
    line: security.jail.sysvipc_allowed=1
  notify: reload sysctl
  tags: sysctl

- name: Ensure helper packages are installed
  pkgng: name={{ item }} state=present
  with_items:
  - ezjail

- name: Set default jail interface
  sysrc:
    name: jail_interface
    value: lo1
  notify: restart ezjail
- name: Set default jail parameters
  sysrc:
    name: jail_parameters
    value: "allow.raw_sockets=1 allow.sysvipc=1"
  notify: restart ezjail
- name: Set default jail exec stop
  sysrc:
    name: jail_exec_stop
    value: "/bin/sh /etc/rc.shutdown"
  notify: restart ezjail

- name: Enable ezjail in rc.conf
  service:
    name: ezjail
    enabled: yes
  notify: restart ezjail

- name: Setup ezjail.conf
  template: src=ezjail.conf dest=/usr/local/etc/ezjail.conf
  notify: restart ezjail

- name: Setup data zpool
  zpool:
    name: "{{ ploy_bootstrap_data_pool_name }}"
    geli: "{{ ploy_bootstrap_geli|bool }}"
    version: "{{ ploy_bootstrap_zpool_version }}"
    devices: "{{ ploy_bootstrap_data_pool_devices }}"
    raid_mode: "{{ ploy_bootstrap_raid_mode }}"

- name: Set data zpool options
  zfs:
    name="{{ ploy_bootstrap_data_pool_name }}"
    state=present
    atime=off
    checksum=fletcher4

- name: Jails ZFS file system
  zfs:
    name="{{ ploy_bootstrap_data_pool_name }}/jails"
    state=present
    mountpoint=/usr/jails

- name: Initialize ezjail (using http proxy)
  command: "ezjail-admin install -h {{ ploy_ezjail_install_host }} -r {{ ploy_ezjail_install_release|default(ansible_distribution_release) }} creates=/usr/jails/basejail"
  when: ploy_http_proxy is defined
  environment:
    http_proxy: "{{ploy_http_proxy}}"
    https_proxy: "{{ploy_http_proxy}}"

- name: Initialize ezjail (may take a while)
  command: "ezjail-admin install -h {{ ploy_ezjail_install_host }} -r {{ ploy_ezjail_install_release|default(ansible_distribution_release) }} creates=/usr/jails/basejail"
  when: ploy_http_proxy is not defined

- name: Create pkg cache folder
  file: dest=/var/cache/pkg/All/ state=directory owner=root group=wheel

# TODO: is this still necessary? and if yes, it should be proxy aware...
- name: Download pkg.txz
  get_url: dest=/var/cache/pkg/All/pkg.txz url={{ pkg_txz_url }}

- { include: bsdploy_flavour.yml, tags: bsdploy_flavour }
